name: flutter_application_1
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  oktoast: ^3.4.0
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.5
  flutter_swiper_view: ^1.1.8
  pull_to_refresh: ^2.0.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/